w <- ins[1]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 13)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 13)
y <- prod(y, x)
z <- sum(z, y) # (up to here, its always: w <- ins[1], x <- 1, y <- ins[1] + 13, z <- ins[1] + 13)

w <- ins[2]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 11)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 10)
y <- prod(y, x)
z <- sum(z, y) # z <- z + (ins[2] + 10) * x, big?. so there are explicit formulas for x, y and z up to this point, and we read in ins[3] next...

w <- ins[3]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 15)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 5)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[4]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 26)
x <- sum(x, -11)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 14)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[5]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 14)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 5)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[6]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 26)
x <- sum(x, 0)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 15)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[7]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 12)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 4)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[8]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 12)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 11)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[9]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 1)
x <- sum(x, 14)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 1)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[10]
x <- prod(x, 0)
x <- sum(x, z)
x <- `%%`(x, 26)
z <- `%/%`(z, 26)
x <- sum(x, -6)
x <- `==`(x, w)
x <- `==`(x, 0)
y <- prod(y, 0)
y <- sum(y, 25)
y <- prod(y, x)
y <- sum(y, 1)
z <- prod(z, y)
y <- prod(y, 0)
y <- sum(y, w)
y <- sum(y, 15)
y <- prod(y, x)
z <- sum(z, y)

w <- ins[11]
x <- as.integer(!((z %% 26L) - 10L == w))
z <- ((z %/% 26L) * (25L * x + 1L)) + ((w + 12L) * x)

w <- ins[12]
x <- as.integer(!((z %% 26L) - 12L == w))
z <- ((z %/% 26L) * (25L * x + 1L)) + ((w + 8L) * x)

w <- ins[13]
x <- as.integer(!((z %% 26L) - 3L == w))
z <- ((z %/% 26L) * (25L * x + 1L)) + ((w + 14L) * x)

w <- ins[14]
x <- as.integer(!((z %% 26L) - 5L == w)) # is ins[14] NOT equal to (five less than the remainder of z/26), which is inside [-5, 20].
z <- ((z %/% 26L) * (25L * x + 1L)) + ((w + 9L) * x) # VALID if y = z = 0, OR y = -z
